export default [
  { username: "john_doe", image: "https://github.com/shadcn.png" },
  { username: "jane_smith", image: "https://github.com/shadcn.png" },
  { username: "alex_wong", image: "https://github.com/shadcn.png" },
  { username: "sara_jones", image: "https://github.com/shadcn.png" },
  { username: "mike_brown", image: "https://github.com/shadcn.png" },
  { username: "mike_brown", image: "https://github.com/shadcn.png" },
  { username: "mike_brown", image: "https://github.com/shadcn.png" },
  { username: "mike_brown", image: "https://github.com/shadcn.png" },
  { username: "mike_brown", image: "https://github.com/shadcn.png" },
  { username: "mike_brown", image: "https://github.com/shadcn.png" },
  { username: "mike_brown", image: "https://github.com/shadcn.png" },
  { username: "mike_brown", image: "https://github.com/shadcn.png" },
  { username: "mike_brown", image: "https://github.com/shadcn.png" },
  { username: "mike_brown", image: "https://github.com/shadcn.png" },
  { username: "mike_brown", image: "https://github.com/shadcn.png" },
  { username: "mike_brown", image: "https://github.com/shadcn.png" },
  { username: "mike_brown", image: "https://github.com/shadcn.png" },
  { username: "mike_brown", image: "https://github.com/shadcn.png" },
  { username: "mike_brown", image: "https://github.com/shadcn.png" },
  { username: "mike_brown", image: "https://github.com/shadcn.png" },
];
